<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
  <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
  <RootNamespace>Asp.Versioning</RootNamespace>
  <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
 </PropertyGroup>

 <ItemGroup>
  <FrameworkReference Include="Microsoft.AspNetCore.App" />
 </ItemGroup>

 <ItemGroup>
  <PackageReference Include="Grpc.AspNetCore" Version="2.80.*" />
  <PackageReference Include="Grpc.Tools" Version="2.80.*">
   <PrivateAssets>all</PrivateAssets>
   <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.*" />
 </ItemGroup>

 <ItemGroup>
  <ProjectReference Include="..\..\src\Asp.Versioning.Grpc.ApiExplorer\Asp.Versioning.Grpc.ApiExplorer.csproj" />
  <ProjectReference Include="..\..\src\Asp.Versioning.Grpc\Asp.Versioning.Grpc.csproj" />
 </ItemGroup>

 <ItemGroup>
  <Protobuf Include="Protos\*.proto" />
 </ItemGroup>

 <ItemGroup>
   <Folder Include="ApiExplorer\" />
 </ItemGroup>

</Project>
