<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   <AssemblyVersion>1.0.0.0</AssemblyVersion>
   <TargetFramework>netstandard2.0</TargetFramework>
   <RootNamespace>Asp.Versioning.Analyzers</RootNamespace>
   <AssemblyTitle>ASP.NET API Versioning Analyzers</AssemblyTitle>
   <Description>The analyzers for API versioning.</Description>
  </PropertyGroup>

  <ItemGroup>
   <InternalsVisibleTo Include="Asp.Versioning.Api.Analyzers.Tests" Key="$(StrongNamePublicKey)" />
  </ItemGroup>

</Project>
