//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Versioning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asp.Versioning.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base64 encoded string required to convert to bytes..
        /// </summary>
        internal static string Base64StringRequired {
            get {
                return ResourceManager.GetString("Base64StringRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete or empty field path..
        /// </summary>
        internal static string EmptyFieldPath {
            get {
                return ResourceManager.GetString("EmptyFieldPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty literal segment..
        /// </summary>
        internal static string EmptyLiteral {
            get {
                return ResourceManager.GetString("EmptyLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty method..
        /// </summary>
        internal static string EmptyMethod {
            get {
                return ResourceManager.GetString("EmptyMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path template has an empty segment..
        /// </summary>
        internal static string EmptyPathSegment {
            get {
                return ResourceManager.GetString("EmptyPathSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &quot;{0}&quot; for enumeration type {1}..
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only literal segments can follow a catch-all segment..
        /// </summary>
        internal static string LiteralOnlyAfterCatchAll {
            get {
                return ResourceManager.GetString("LiteralOnlyAfterCatchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration must end with &apos;s&apos;..
        /// </summary>
        internal static string MalformedDuration {
            get {
                return ResourceManager.GetString("MalformedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map field requires repeating keys and values..
        /// </summary>
        internal static string MapRequiresRepeating {
            get {
                return ResourceManager.GetString("MapRequiresRepeating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find matching field for body &quot;{0}&quot; on {1}..
        /// </summary>
        internal static string MissingBodyField {
            get {
                return ResourceManager.GetString("MissingBodyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find matching field for route parameter &quot;{0}&quot; on {1}..
        /// </summary>
        internal static string MissingFieldForRouteParam {
            get {
                return ResourceManager.GetString("MissingFieldForRouteParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find matching field for response body &quot;{0}&quot; on {1}..
        /// </summary>
        internal static string MissingResponseBodyField {
            get {
                return ResourceManager.GetString("MissingResponseBodyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &apos;{0}&apos; when parsing path template..
        /// </summary>
        internal static string MissingTemplateChar {
            get {
                return ResourceManager.GetString("MissingTemplateChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The body field &quot;{0}&quot; references a nested field. The body field name must be on the top-level request message..
        /// </summary>
        internal static string NestedBodyField {
            get {
                return ResourceManager.GetString("NestedBodyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response body field &quot;{0}&quot; references a nested field. The response body field name must be on the top-level request message..
        /// </summary>
        internal static string NestedResponseBodyField {
            get {
                return ResourceManager.GetString("NestedResponseBodyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable cannot be nested..
        /// </summary>
        internal static string NestedVariable {
            get {
                return ResourceManager.GetString("NestedVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set multiple values onto a non-repeating field..
        /// </summary>
        internal static string NonRepeatingMultipleValues {
            get {
                return ResourceManager.GetString("NonRepeatingMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path segment must end with a &apos;/&apos;..
        /// </summary>
        internal static string PathMustEndWithSlash {
            get {
                return ResourceManager.GetString("PathMustEndWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path template must start with a &apos;/&apos;..
        /// </summary>
        internal static string PathMustStartWithSlash {
            get {
                return ResourceManager.GetString("PathMustStartWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing path template &quot;{0}&quot;..
        /// </summary>
        internal static string RoutePatternParseError {
            get {
                return ResourceManager.GetString("RoutePatternParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String required to convert to enumeration..
        /// </summary>
        internal static string StringRequiredForEnum {
            get {
                return ResourceManager.GetString("StringRequiredForEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route template should not end with a &apos;/&apos;..
        /// </summary>
        internal static string TemplateShouldNotEndWithSlash {
            get {
                return ResourceManager.GetString("TemplateShouldNotEndWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error when updating variable..
        /// </summary>
        internal static string UnexpectedRouteVariableError {
            get {
                return ResourceManager.GetString("UnexpectedRouteVariableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path template wasn&apos;t parsed to the end..
        /// </summary>
        internal static string UnparsedRoutePattern {
            get {
                return ResourceManager.GetString("UnparsedRoutePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type: {0}.
        /// </summary>
        internal static string UnsupportedType {
            get {
                return ResourceManager.GetString("UnsupportedType", resourceCulture);
            }
        }
    }
}
