// Copyright (c) .NET Foundation and contributors. All rights reserved.

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: asp/api/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Asp.Versioning {

  /// <summary>Holder for reflection information generated from asp/api/annotations.proto</summary>
  public static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for asp/api/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlhc3AvYXBpL2Fubm90YXRpb25zLnByb3RvEgdhc3AuYXBpGiBnb29nbGUv",
            "cHJvdG9idWYvZGVzY3JpcHRvci5wcm90bzowCgd2ZXJzaW9uEh0uZ29vZ2xl",
            "LnByb3RvYnVmLkZpZWxkT3B0aW9ucxjFigMgAygJQhGqAg5Bc3AuVmVyc2lv",
            "bmluZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { AnnotationsExtensions.Version }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of asp/api/annotations.proto</summary>
  public static partial class AnnotationsExtensions {
    /// <summary>
    /// an api version the field is included in.
    /// repeat the option to include the field in more than one version.
    /// included in all versions when absent
    /// </summary>
    public static readonly pb::RepeatedExtension<global::Google.Protobuf.Reflection.FieldOptions, string> Version =
      new pb::RepeatedExtension<global::Google.Protobuf.Reflection.FieldOptions, string>(50501, pb::FieldCodec.ForString(404010));
  }

}

#endregion Designer generated code
