//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Versioning {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class MvcSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcSR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asp.Versioning.MvcSR", typeof(MvcSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An action method with the name &apos;{0}&apos; could not be found. The method must be public, non-static, and not have the NonActionAttribute applied..
        /// </summary>
        internal static string ActionMethodNotFound {
            get {
                return ResourceManager.GetString("ActionMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple action methods with the name &apos;{0}&apos; were found, but could not be resolved using the provided arguments..
        /// </summary>
        internal static string AmbiguousActionMethod {
            get {
                return ResourceManager.GetString("AmbiguousActionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API version conventions cannot be applied to the controller type {0} using both typed and untyped convention builders..
        /// </summary>
        internal static string ConventionStyleMismatch {
            get {
                return ResourceManager.GetString("ConventionStyleMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; must refer to a controller action method..
        /// </summary>
        internal static string InvalidActionMethodExpression {
            get {
                return ResourceManager.GetString("InvalidActionMethodExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not implement the {1} interface..
        /// </summary>
        internal static string RequiredInterfaceNotImplemented {
            get {
                return ResourceManager.GetString("RequiredInterfaceNotImplemented", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple API versions were inferred from the namespace '{0}'. The convention must match exactly zero or one API versions..
        /// </summary>
        internal static string MultipleApiVersionsInferredFromNamespaces
        {
            get
            {
                return ResourceManager.GetString( "MultipleApiVersionsInferredFromNamespaces", resourceCulture );
            }
        }
    }
}
