# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/dotnet/.devcontainer/base.Dockerfile

# [Choice] .NET version: use "latest" or a specific version like "10.0"
ARG VARIANT="10.0"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet