# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.177.0/containers/dotnet/.devcontainer/base.Dockerfile

# [Choice] .NET version: 7.0, 6.0, 5.0
ARG VARIANT="8.0"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet