<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

 <PropertyGroup>
  <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
 </PropertyGroup>

 <ItemGroup Label="ASP.NET Web API">
  <PackageVersion Include="Microsoft.AspNet.WebApi.OwinSelfHost" Version="5.3.0" />
  <PackageVersion Include="Swashbuckle.Core" Version="5.6.0" />
 </ItemGroup>

 <ItemGroup Label="ASP.NET Core">
  <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />
  <PackageVersion Include="Grpc.Tools" Version="2.80.0" />
  <PackageVersion Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.10" />
  <PackageVersion Include="Microsoft.AspNetCore.OData" Version="10.0.0-preview.2" />
  <PackageVersion Include="Microsoft.Extensions.ApiDescription.Server" Version="11.0.0-preview.6.26359.118" />
  <PackageVersion Include="Scalar.AspNetCore" Version="2.16.13" />
  <PackageVersion Include="Scalar.AspNetCore.Microsoft" Version="2.16.13" />
 </ItemGroup>

</Project>