// Copyright (c) .NET Foundation and contributors. All rights reserved.

namespace Asp.Versioning.OpenApi.Simulators;

using Microsoft.AspNetCore.Mvc;

// declared internal so that the default controller feature provider, which only discovers public types, does not
// add it to the documents generated by the other tests in this assembly. it is registered explicitly instead
#pragma warning disable CA1812
#pragma warning disable CA1822

[ApiController]
[ApiVersion( 1.0 )]
[ApiVersion( 2.0 )]
[Route( "api/orders" )]
internal sealed class OrdersController : ControllerBase
{
    [HttpGet( "{id:int}" )]
    public Order Get( int id ) => new() { Id = id };
}