//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Versioning {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asp.Versioning.SR", typeof(SR).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified API group version &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ApiVersionBadGroupVersion {
            get {
                return ResourceManager.GetString("ApiVersionBadGroupVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified API version status &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string ApiVersionBadStatus {
            get {
                return ResourceManager.GetString("ApiVersionBadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified API version is invalid..
        /// </summary>
        internal static string ApiVersionInvalidFormat {
            get {
                return ResourceManager.GetString("ApiVersionInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key cannot be empty..
        /// </summary>
        internal static string EmptyKey {
            get {
                return ResourceManager.GetString("EmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first character must be a letter..
        /// </summary>
        internal static string FirstCharMustBeLetter {
            get {
                return ResourceManager.GetString("FirstCharMustBeLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was not in a correct format..
        /// </summary>
        internal static string InvalidFormatString {
            get {
                return ResourceManager.GetString("InvalidFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters, numbers, &apos;-&apos;, and &apos;_&apos; are allowed..
        /// </summary>
        internal static string InvalidLinkKey {
            get {
                return ResourceManager.GetString("InvalidLinkKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The header contains invalid or missing values..
        /// </summary>
        internal static string InvalidOrMalformedHeader {
            get {
                return ResourceManager.GetString("InvalidOrMalformedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The relation type for a sunset policy link must be &quot;sunset&quot;..
        /// </summary>
        internal static string InvalidSunsetRelationType {
            get {
                return ResourceManager.GetString("InvalidSunsetRelationType", resourceCulture);
            }
        }
    }
}
