// Copyright (c) .NET Foundation and contributors. All rights reserved.

namespace Asp.Versioning.OpenApi.Transformers;

using Asp.Versioning.OpenApi.Simulators;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using System.Net.Http.Json;
using System.Text.Json.Nodes;

public class MemberVisibilityTest
{
    [Fact]
    public async Task minimal_api_should_only_describe_members_visible_to_api_version()
    {
        // arrange
        using var app = NewApplication();
        var cancellationToken = TestContext.Current.CancellationToken;

        await app.StartAsync( cancellationToken );

        using var client = app.GetTestClient();

        // act
        var v1 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v1.json", cancellationToken );
        var v2 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v2.json", cancellationToken );

        // assert
        MembersOf( v1, nameof( Order ) ).Should().BeEquivalentTo( "id", "customer", "shipTo" );
        MembersOf( v2, nameof( Order ) ).Should().BeEquivalentTo( "id", "customer", "shipTo", "notes" );
    }

    [Fact]
    public async Task minimal_api_should_only_describe_nested_members_visible_to_api_version()
    {
        // arrange
        using var app = NewApplication();
        var cancellationToken = TestContext.Current.CancellationToken;

        await app.StartAsync( cancellationToken );

        using var client = app.GetTestClient();

        // act
        var v1 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v1.json", cancellationToken );
        var v2 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v2.json", cancellationToken );

        // assert
        MembersOf( v1, nameof( Address ) ).Should().BeEquivalentTo( "street" );
        MembersOf( v2, nameof( Address ) ).Should().BeEquivalentTo( "street", "country" );
    }

    [Fact]
    public async Task controller_should_only_describe_members_visible_to_api_version()
    {
        // arrange
        using var app = NewControllerApplication();
        var cancellationToken = TestContext.Current.CancellationToken;

        await app.StartAsync( cancellationToken );

        using var client = app.GetTestClient();

        // act
        var v1 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v1.json", cancellationToken );
        var v2 = await client.GetFromJsonAsync<JsonNode>( "/openapi/v2.json", cancellationToken );

        // assert
        MembersOf( v1, nameof( Order ) ).Should().BeEquivalentTo( "id", "customer", "shipTo" );
        MembersOf( v2, nameof( Order ) ).Should().BeEquivalentTo( "id", "customer", "shipTo", "notes" );
        MembersOf( v1, nameof( Address ) ).Should().BeEquivalentTo( "street" );
        MembersOf( v2, nameof( Address ) ).Should().BeEquivalentTo( "street", "country" );
    }

    private static WebApplication NewControllerApplication()
    {
        var builder = WebApplication.CreateBuilder();

        builder.WebHost.UseTestServer();

        // the controller is internal so that it stays out of the documents generated by the other tests, which
        // means the default feature provider will not discover it and it has to be registered explicitly
        builder.Services.AddControllers()
                        .ConfigureApplicationPartManager( m =>
                        {
                            m.ApplicationParts.Clear();
                            m.FeatureProviders.Add( new OrdersControllerFeatureProvider() );
                        } );

        builder.Services.AddApiVersioning()
                        .AddMvc()
                        .AddApiExplorer( options => options.GroupNameFormat = "'v'VVV" )
                        .AddOpenApi();

        var app = builder.Build();

        app.MapControllers();
        app.MapOpenApi().WithDocumentPerVersion();

        return app;
    }

    private static WebApplication NewApplication()
    {
        var builder = WebApplication.CreateBuilder();

        builder.WebHost.UseTestServer();
        builder.Services.AddApiVersioning()
                        .AddApiExplorer( options => options.GroupNameFormat = "'v'VVV" )
                        .AddOpenApi();

        // keep controllers declared elsewhere in this assembly out of the document
        builder.Services.AddMvcCore().ConfigureApplicationPartManager( m => m.ApplicationParts.Clear() );

        var app = builder.Build();
        var api = app.NewVersionedApi( "Orders" )
                     .MapGroup( "/orders" )
                     .HasApiVersion( 1.0 )
                     .HasApiVersion( 2.0 );

        api.MapGet( "{id:int}", ( int id ) => new Order() );
        app.MapOpenApi().WithDocumentPerVersion();

        return app;
    }

    private static IEnumerable<string> MembersOf( JsonNode document, string schema ) =>
        document!["components"]!["schemas"]![schema]!["properties"]!.AsObject().Select( p => p.Key );
}